//
//  burgerData.swift
//  recipe
//
//  Created by Amgad ElNezamy on 13/05/2023.
//

import SwiftUI
let burgerData : [Burger] = [

    Burger(title: "Cauliflower & mayo burgers", image: "CauliflowerCurriedMayoBurgers", Ingredients: "1 small cauliflower, 3 tbsp olive oil, 2 tbsp medium curry powder ,2 large tomatoes, finely chopped ,1 red onion, finely chopped ½ bunch of coriander, finely chopped ,2 tbsp mayonnaise ,3 tbsp Greek yogurt ,2 tbsp curry paste ,4 burger buns, 2 handfuls of bombay mix, (optional)", method: "Heat the oven to 200C/180C fan/gas 6. Pull the leaves off the cauliflower and cut off the base, then slice into 2cm-thick steaks. Mix the oil with the curry powder. Lay the cauliflower steaks on a flat baking tray lined with foil. Brush each one generously with the curry oil on both sides, and sprinkle with salt before roasting for 25-30 mins until tender. In a bowl, mix together the tomatoes, onion, coriander and a pinch of salt. In a second bowl mix together the mayonnaise, yogurt and curry paste. Toast the buns cut-side down in a dry frying pan. Top each bun with a dollop of curried mayo, the cauliflower steak, some more curried mayo, the tomato and onion mix and some bombay mix, if you like.",color: Color("Cauliflower01")),

    Burger(title: "Monday night burgers & slaw", image:"Monday night burgers & slaw", Ingredients: "2 Tesco Plant Chef Meat-Free Burgers ,2 burger buns, split 1 large vine tomato, sliced small handful of rocket or spinach ¼ cabbage (white, red, sweetheart or spring greens), finely sliced 1 carrot, grated ½ red onion, finely sliced, 4 tbsp vegan mayonnaise, plus extra to serve squeeze of lemon juice, 1 tsp Dijon mustard small handful of chives, parsley or coriander, finely chopped", method: "Heat the grill to medium-high. Put the Tesco Plant Chef Meat-Free Burgers on a baking tray and grill for 4-5 mins each side until golden and crisp. Toast the buns cut-side up alongside the burgers on the tray for the last 2-3 mins. Meanwhile, toss the slaw ingredients with some seasoning. Taste, and add a little more lemon or mustard, if you like. Spread a little mayo on the burger bun bases, add a tomato slice and a burger. Add a spoonful of the slaw. Top with some rocket or spinach, and add the burger lids. Serve with the remaining slaw on the side.", color: Color("Monday night02")),

    Burger(title: "Moroccan lamb burgers", image: "Moroccan-Burgers", Ingredients: "1 onion, roughly chopped 2½cm piece ginger, roughly chopped 2 garlic cloves, roughly chopped handful of fresh coriander 2 tsp ground coriander 2 tsp ground cumin 1 tsp cinnamon 75g ready-to-eat dried apricots, roughly chopped 500g lean lamb mince", method: "Blend the onion, ginger, garlic and fresh coriander in a food processor until finely chopped. Add the spices, apricots, lamb and seasoning. Blend until slightly chunky. Shape the lamb mixture into six burgers. Cook under a medium-hot grill for 4-5 mins each side until cooked through. Serve in wholemeal buns with the lettuce, tomato, sliced red onion and mayo.", color: Color("Moroccan-Burgers01")),


    Burger(title: "BBQ aubergine & black bean burgers", image: "Pulled BBQ aubergine & black bean burgers", Ingredients: "2 large aubergines, pricked all over with a fork 1 tbsp olive oil 1 large onion, thinly sliced 1 heaped tsp garlic granules 2 tsp smoked paprika 1 tbsp demerara sugar 1 tsp dried oregano 5 tbsp barbecue sauce 400g can black beans, drained 4 burger buns, toasted and lightly buttered red onion or pink pickled onion, shredded lettuce, coleslaw and corn on the cob, to serve (optional)", method: "Heat the grill to high and grill the aubergine, turning occasionally, until blackened and soft all over, about 20-30 mins. Set aside to cool. Meanwhile, heat the oil in a large ovenproof pan over a medium heat, add the onion and fry until softened and golden, about 10 mins. Heat the oven to 200C/180C fan/gas 6. Peel the skin from the cooled aubergine and discard it, or scoop out the flesh using a spoon, then put in the pan with the onion. Add the garlic granules, paprika, sugar, oregano, 1 tsp sea salt and 1 tsp black pepper. Stir until aromatic, then mix in the barbecue sauce along with the black beans. Season and bake until the sauce is rich and thick, and the aubergine resembles pulled pork – about 10-15 mins. Pile into the burger buns with the red onion or pink pickled onion and any other burger fillings you like. Enjoy with coleslaw and corn on the cob on the side, if you like.", color: Color("Black-bean01")),

    Burger(title: "Beef burgers", image: "Next-level-burger", Ingredients: "[1]- 250g plain white flour,[2]- plus extra for dusting 20g golden caster sugar [3]- 5g fast-action dried yeast [4]- 150 ml milk [5]- 1 egg, [6]- beaten 50g butter,[7]- softened sesame seeds, for sprinkling (optional) [8]- 600g dry-aged chuck steak, cut into large chunks toppings of your choice, such as cheese, onions, tomatoes or lettuce. [9]- 3 tbsp mayonnaise [10]- 2 tbsp ketchup or sriracha (or use 1 tbsp of each). [11]- 1 tbsp American mustard [12]- 1 small gherkin, finely chopped, plus extra to serve large pinch of garlic granules", method: "To make your own buns, tip the flour, sugar, yeast and 1 tsp salt into the bowl of a stand mixer fitted with a paddle attachment. With the motor running on medium speed, gradually add the milk, then half the egg. Leave to mix for a few minutes, then add the butter, a little at a time, until the dough is elastic and shiny – about 5 mins. Alternatively, do this in a bowl using an electric whisk. Divide the dough into four and roll each piece into a round on a lightly floured surface. Arrange well spaced apart on a baking tray lined with baking parchment. Press down gently to spread them out a little and leave in a warm place for 2 hrs, or in the fridge overnight, until doubled in size. Heat the oven to 200C/180C fan/gas 6. Brush the remaining egg over the buns and scatter with the sesame seeds, if using. Bake for 13-15 mins until risen and golden. Leave to cool. Can be made up to a day ahead. For the sauce, stir together all the ingredients and set aside. Can be made up to a day ahead and kept chilled. To make the burgers, chill the chuck steak in the freezer alongside the blade and, if it fits, bowl of a food processor for 30 mins until the meat is firm but not frozen solid. Working quickly, tip half the chilled beef into the food processor and pulse eight to 10 times until the meat is minced, being careful not to overwork it. Tip the mince onto a tray and repeat with the remaining steak, then mix both lots together with ½ tsp salt. Divide into four portions and gently form each into a loose patty a bit wider than the buns. Don’t overwork it. Cook the burgers as soon as possible after forming. Set a large, heavy frying pan over a medium heat. Split the buns and toast, cut-side down, in the pan (you may need to do this in batches). Remove to a plate, then sear the burgers, pressing them down with a spatula as they cook, for 4-5 mins on each side for medium rare or 6-7 mins for medium. Top with cheese, if you like, after flipping them. When the burgers are cooked, assemble as preferred with the buns, toppings of your choice and the burger sauce.", color: Color("Monday night01")),

    Burger(title: "Black bean burger", image: "Black-bean-burgers", Ingredients: "75g wholemeal bread ,or sourdough 75g walnuts 400g sweet potato 400g can black beans, drained 1 tsp smoked paprika 1 tsp ground cumin 1/2 tsp onion granules 1 tbsp tomato purée 2 tbsp rapeseed oil, to fry ½ cucumber, halved, deseeded and sliced on an angle 2 large carrots (about 300g) peeled into ribbons small bunch coriander, finely chopped 2 tbsp lime juice 1 tbsp rapeseed oil 4 sourdough burger buns 2 large tomatoes, thickly sliced 1 avocado, peeled, stoned and sliced 50g rocket coconut yogurt or burger sauce of choice", method: "Put the wholemeal bread and walnuts in a food processor and pulse to make fine crumbs. Prick the sweet potatoes with a fork and microwave for 5-10 mins until soft. Cut in half and scrape the cooked centres into the food processor with the bread and walnut crumbs. Make sure the beans are drained thoroughly then add them to the processor with the paprika, cumin, onion granules, and tomato puree. Season generously and pulse until the mixture is mostly smooth and holding together. Divide the mix into 4 patties and chill for 20 mins to firm up. Meanwhile make the side salad by mixing the cucumber, carrot, coriander, lime juice and rapeseed oil together. Season and put to one side. Heat the oil in a large non-stick frying pan over a medium heat. Add the patties and fry for 4-5 mins on each side until golden and hot through. Place a small handful of rocket into each burger bun. Top with the tomato slices, burgers, and then avocado. Add a dollop of coconut yogurt or burger sauce of your choice. Serve with the carrot and cucumber salad alongside.", color: Color("Black-bean02")),

    Burger(title: "beetroot & quinoa burgers", image: "Beetroot-quinoa-burger", Ingredients: "2 tbsp rapeseed oil 1 red onion, finely chopped 1 tbsp cumin seeds 2 garlic cloves, finely chopped 200g quinoa, cooked 2 large cooked beetroot (150g), finely grated and liquid reserved 50g plain flour 2 tbsp milled flaxseed ½ small bunch of coriander, plus a few leaves to serve 25ml beetroot preserving liquid ½ lemon, juiced 100g low-fat soy yogurt 50ml extra virgin olive oil 200g rocket", method: "Heat the oven to 220C/200C fan/gas 7. Put 1 tbsp of the rapeseed oil in a small frying pan and tip in the onion, cumin and garlic, then fry over a medium heat for 8 mins until softened and golden. Tip into a bowl. Add the cooked quinoa, beetroot, flour, flaxseed and coriander, and mix until combined. Season lightly. Leave to sit for 5 mins to bind. Divide the mixture into four – it will be quite loose – then, using wet hands, shape them into patties. Put the burgers on a lined baking tray and put in the oven for 15 mins. Turn them over and cook for another 10 mins. Meanwhile, make the salad dressing. Whisk together the beetroot liquid, lemon juice, yogurt and oil, and season. To serve, pile the rocket onto plates and place a burger on top. Drizzle over the dressing and scatter over the extra coriander.",color: Color("Beetroot01")),

    Burger(title: "Double cheeseburger & secret sauce", image: "Big-double-cheeseburger", Ingredients: "1 small onion, finely chopped 4 sesame-topped burger buns 300g steak mince 1 tbsp sunflower oil small wedge of iceberg lettuce, finely shredded 2 slices of mild cheddar or burger cheese 1 gherkin sliced lengthways oven fries, to serve 100g mayonnaise 1 tbsp American mustard large pinch garlic granules large pinch onion granules ¼ tsp smoked paprika 1 tbsp white wine vinegar 1 tsp pickle relish or finely chopped gherkin", method: "ip the onions into a small bowl and pour over boiling water from the kettle until just covered. Leave to cool. Put all the sauce ingredients in another small bowl, then add 1 tbsp of the cooled onion water and mix until everything is evenly combined. Set aside. Halve two of the burger buns, then cut a thick slice from the middles of the other two buns. Toast or grill the middle slices on both sides and the other buns only on the cut sides, then set aside. Heat the oven to 100C/80C fan/gas 2. Divide the mince into four loose piles and season. Heat ¼ tbsp of the oil in a heavy frying pan or skillet over a high heat and put one of the piles of beef in the pan. Working quickly, cover with a square of baking parchment and carefully use a second pan to press the beef patties down – be careful of the heat and rising steam as you do this. Keep the patties pressed down for about 10 seconds, then remove the weight and the paper, and leave the burger to cook for 2 mins more. Turn the patties and press down using a spatula, cooking for another 1 min. Transfer to a tray and keep warm in the oven while you cook the other burgers in the same way. When all the patties are cooked, it’s time to assemble the burgers. Spread some sauce over the bun bases, scatter with onions, then add lettuce, followed by a cheese slice, then a patty, a few gherkin slices and a middle slice of toasted bun. Spread over more sauce, then add more onions, lettuce, another patty and the bun tops. Serve with the oven fries and extra sauce on the side, if you like.", color: Color("cheeseburger01")),

    Burger(title: "Lemon & herb chicken burger", image: "Lemon-and-herb-chicken", Ingredients: "4 skinless, boneless chicken breasts 8 rashers smoked bacon 4 burger buns, split 4 slices of your favourite cheese (optional) 2 avocados, halved, stoned, peeled and sliced 2 tomatoes, sliced 4 handfuls of lettuce leaves 1 garlic clove 2 tsp chopped thyme leaves, or 1 tsp dried thyme ½ lemon, juiced 3 tbsp olive oil 3 tbsp mayonnaise 1 tbsp lemon juice 1 tsp mustard small splash of chilli sauce (optional)", method: "First, make the marinade. Crush the garlic with the thyme and a pinch of salt using a pestle and mortar. Add the lemon juice, olive oil and plenty of cracked black pepper and mash together to combine. Lay the chicken breasts out on a board and flatten slightly using a rolling pin until they are an even thickness. Transfer to a container with the marinade, then seal, shake and chill until needed, or for up to 1 hr. Light the barbecue and wait until the coals are ashen, or heat a gas barbecue to medium. Mix the sauce ingredients together in a small bowl and keep chilled. Cook the bacon on the barbecue for 3-4 min until crisp. Remove to a plate and set aside. Toast the cut side of the buns where you grilled the bacon to soak up the fat, then remove and set aside. Barbecue the marinated chicken breasts for 4-5 mins on each side until lightly charred. Top each with a slice of cheese, if using, and cook for a few minutes more until the cheese has melted and the chicken is cooked through (a probe thermometer should read at least 65C). Spread the base of each bun with the sauce, then top with the avocado slices, tomatoes, chicken, bacon and lettuce. Sandwich with the bun tops, press down lightly and serve.", color: Color("Lemon-and-herb02"))
    


]
